services:
  - type: web
    name: keyword-rank-api
    env: node
    plan: free
    buildCommand: |
      echo "Entering backend directory" && cd backend \
      && echo "Installing deps (including dev)" && npm install --production=false \
      && echo "Running TypeScript build" && npm run build \
      && echo "Listing dist" && ls -R dist || echo "dist missing"
    startCommand: bash -lc "cd backend && node dist/index.js"
    autoDeploy: true
    envVars:
      - key: SERPAPI_KEY
        sync: false
